services:
    libdse-api:
      image: ghcr.io/nikpau/libdse:latest
      restart: unless-stopped
      volumes:
        - /opt/speech-enhancement/data:/app/data:ro
    
    caddy-gateway:
      build:
        context: .
        dockerfile: Dockerfile.caddy
      restart: unless-stopped
      env_file:
        - .env
      ports:
        - "80:80"
        - "443:443"
        - "443:443/udp" # HTTP/3 support
      volumes:
        - ./Caddyfile:/etc/caddy/Caddyfile
        - caddy_data:/data
        - caddy_config:/config
        - ${PORTFOLIO_STATIC_HTML_TARGET}:/srv/frontend:ro # Mount static HTML files as read-only
      depends_on:
        - libdse-api

volumes:
  caddy_data:
  caddy_config:
